version: "3.9"
services:
  ### Prefect Orion API
  orion:
    image: prefecthq/prefect:2.14-python3.10
    restart: always
    volumes:
      - prefect:/root/.prefect
    command: ["prefect", "server", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    ports:
      - "4200:4200"
    networks:
      - prefect-network

networks:
  prefect-network:
    driver: bridge

volumes:
  prefect: